#!/bin/bash

	. fns_EDIT
	. fns_BASE

	#!/bin/bash

	# hardlink this file to "man_WHATEVER"
	# its cheaper than a symb link (1 inode)
	# add any MANPATH you think you might need

# set -x
	 rhs=""
	 mid=""
	 opts=""
	name=$1
	if rhs=$(expr match "$name" '.*_\(.*\)')
	then
		mid=$(expr match "$name" '\(.*\)_.*')
		opts=$mid
		case "$mid"
		in
		 a|k) opts=-$mid
		;; 
		esac
		mid="$mid"_
	else
		rhs=$name
	fi
	lhs=man_
	name2="${lhs}${mid}${rhs}"

	echo "WILL be $name2"
	echo "# TEST IT #"

	ask_do \
	man $opts $rhs
	#

	echo "
	If that worked, you now install the man_PAGE command link

	man_ is a script the detects its own name
	man_PAGE is the name of the link
	man_ is the seed link, upgrade this script to link_to_nearest_same_vfs
	// EG // ../../go_man/man_
	// EG // D0=./same_mounted_fs_mount_point/. or /../.pwd
	// otherwise create a new one with DATE

# INSTALL IT #
"

	ask_do \
	ln man_man "$name2"
	#

exit
