#!/bin/bash

	. fns_EDIT
	. fns_BASE

# set -x
	 rhs=""
	 mid=""
	 opts=""
	fn_BASE_rd - name
	name=${1:-$name}
	fn_BASE_wr - name
#	fn_EDIT_prompt_var MAN_9_PAGE_NAME name
	# actually this ignores $name just goes for varfile[name]
	fn_BASE_edit - name

	if rhs=$(expr match "$name" '.*_\(.*\)')
	then
		mid=$(expr match "$name" '\(.*\)_.*')
		opts=$mid
		case "$mid"
		in
		 a|k) opts=-$mid
		;; 
		esac
		mid="$mid"_
	else
		rhs=$name
	fi
	lhs=man_
	name2="${lhs}${mid}${rhs}"

	echo "WILL be $name2"
	echo "# TEST IT #"

	ask_do \
	man $opts $rhs
	#

	echo "
	If that worked, you now install the man_PAGE command link

	man_ is a script the detects its own name
	man_PAGE is the name of the link
	man_ is the seed link, upgrade this script to link_to_nearest_same_vfs
	// EG // ../../go_man/man_
	// EG // D0=./same_mounted_fs_mount_point/. or /../.pwd
	// otherwise create a new one with DATE

# INSTALL IT #
"

	ask_do \
	ln man_man "$name2"
	#

exit
